### PR TITLE
Remove use of deprecated Future.onSuccess

### PR DESCRIPTION
**Pull request by NthPortal**
See scala/scala#6319

### CODE REVIEW

**Comment by SethTisue** [comment]
couldn't we use `.foreach` here instead of `.onComplete`?

**Comment by NthPortal** [comment]
Probably, yeah. I'll add a switch to that as a second commit, and then squash if it builds

**Comment by SethTisue** [comment]
thanks, Nth!

**Comment by NthPortal** [comment]
No problem!

**Pull request merged**
