### PR TITLE
build.sh: try to support # tags for single Scala version releases again

### PR DESCRIPTION
**Pull request by Sciss**

### CODE REVIEW

**Comment by SethTisue** [comment]
I suggest that we not bring this back. It wasn't necessarily a terrible way to do things, but we're doing it differently now in all other modules.

The new way to backpublish, as per #112 and #127, is to remove the unwanted matrix entries from `.travis.yml`, then tag and push the commit (tagged, but not on any branch). I did this recently over at scala/scala-parallel-collections#143 and it worked fine.

Now, you're the maintainer here and if you like, you can stick with the old method. But I don't recommend it, because the downside is basically that I can't keep multiple ways of doing this in my head, and help maintain multiple ways, we have a bunch of these modules and it's a lot easier to help out with them if they're all the same. (I mean, I wouldn't refuse to answer questions about nonstandard setups, but I wouldn't be available to actually help dig into it if something goes wrong, either.)

**Comment by SethTisue** [comment]
P.S. there is now a breadcrumb about this on https://github.com/scala/sbt-scala-module/issues/16

**Comment by Sciss** [comment]
Ok, I can revert, do the pushing as you say. Can you clear the sonatype staging, so I can go ahead with that?

**Comment by Sciss** [comment]
I am ready to merge and push the tag

**Comment by SethTisue** [comment]
whoops — this shouldn't have been merged to the `work` branch — the idea is to tag the commit and push the tag, without pushing the commit to any branch

I pushed reversions to the `work` branch, so now we're back to normal, I think

**Comment by Sciss** [comment]
I don't understand. You cannot push a tag if you don't push a corresponding commit? Or should a new branch be created?

**Comment by SethTisue** [comment]
The commit should be on _no branch at all_. It's sufficient that it have an associated tag.

You tag the commit and push the tag: `git push origin <tag-name>`. (Pushing the tag pushes the commit as well.)

**Comment by Sciss** [comment]
Thanks, I didn't know about that; https://stackoverflow.com/questions/9265278/what-happens-if-i-push-a-tag-for-a-commit-that-hasnt-been-pushed

**Comment by SethTisue** [comment]
Yeah, it's a bit odd :-)

**Pull request merged**
