### PR TITLE
Implemented DesktopPane and InternalFrame

### LINKED ISSUE #119: Missing support for JInternalFrame and JDesktopPane
`scala-swing` does not have any support for the `JInternalFrame` and `JDesktopPane` elements, which provide support for nesting windows inside a frame. While `JDesktopPane` can simply be `Component.wrap`'d, `JInternalFrame` has its own event hierarchy that is analogous to but separate from window events, and `scala-swing` does not provide any mappings for these.

### PR DESCRIPTION
**Pull request by reggert**
This feature adds support for `JDesktopPane` and `JInternalFrame`, as well as the latter's event hierarchy, to resolve #119 .

I branched directly off the `v2.1.1` tag to allow it to be applied as a patch for the latest release. I can rebase onto `work` if necessary, though, but there should be no conflicts either way.

I tried to follow the conventions used by `Window`/`RichWindow`/`Frame` as much as possible, and avoided implementing wrappers for any parts of the Swing API that were documented as not intended for use by applications. It's possible that I may have neglected to implement some obscure feature, but I think I've covered all the likely use cases.

I originally implemented this within and tested it with a separate project that I am working on, and everything I tried out seems to be working.

Note that `JInternalFrame` does not extend the AWT `Window` class, so there was no way (that I could see) to integrate `InternalFrame` directly into the `Window`/`RichWindow` hierarchy.

### CODE REVIEW

**Comment by Sciss** [comment]
Thank you! I will only be able to review this in the first week of June. If someone else wants to go ahead, please do so. Please remind me if I don't follow up on this.

**Comment by reggert** [comment]
Anyone had a chance to look at this yet?

**Comment by benhutchison** [comment]
Hi Richard, rest assured I want to ensure your contribution makes it into
ScalaSwing. I'd like to wait for @sciss to review (as unlike) myself he's
an active ScalaSwing user and will likely do a better review. He said early
June so let's give him some time. But if that doesn't happen I'll ensure it
gets merged.

**Comment by Sciss** [comment]
Thanks for the patience. I had a brief look, in general it looks good. Of course one question would be if there is a common interface to Frame and InternalFrame, which could fix a design mistake (IMO) in Java Swing; but this could be also added at a later point.

The `DragMode` style is a bit different than the rest of Scala Swing when it comes to wrapping constants. I think it should be an `Enumeration` like everywhere else (e.g. `FileChooser.Result`, `FileChooser.SelectionMode`, `BorderPanel.Position`, `Alignment`, etc.)

Apart from this change, I would be happy to merge. If a second pair of eyes is available, it would be great, but at least from cursory examination, I cannot see any issues.

**Comment by Sciss** [comment]
Another question is if you have already signed the CLA? (See https://github.com/scala/scala-swing/issues/51#issuecomment-261242236). To avoid future problems, we require this from any first time contributor.

**Comment by reggert** [comment]
CLA signed.

**Comment by reggert** [comment]
I've converted `DragMode` to an `Enumeration` and added some documentation for it.

**Comment by reggert** [comment]
Last (force) push was just tweaks to the wording of the `DragMode` documentation.

**Pull request merged**
