### PR TITLE
Fix Scala 2.13.0-RC1 compilation, fix a number of simple bugs / enhancements

### PR DESCRIPTION
**Pull request by Sciss**
If you're fine with these, we can then tag the version. build.sbt already has version set to 2.1.1

### CODE REVIEW

**Comment by SethTisue** [comment]
The build changes LGTM

**Comment by Sciss** [comment]
I pushed the corresponding tag: https://github.com/scala/scala-swing/releases/tag/v2.1.1

**Comment by SethTisue** [comment]
🎉

**Comment by Sciss** [comment]
I think someone needs to release that on sonatype, AFAICS the artifacts have been uploaded.

**Comment by Philippus** [comment]
@SethTisue could you do the honors?

**Comment by SethTisue** [comment]
sorry for the delay. artifacts should appear soon at https://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.13.0-RC1/2.1.1

**Comment by SethTisue** [comment]
and there they are!

scala/make-release-notes@2d559a65b940d7c90ed2b732fdc935594d0579e8

**Pull request merged**
