### PR TITLE
clean up: remove procedure syntax, add return types

### PR DESCRIPTION
**Pull request by Sciss**
- deprecated procedure syntax has been removed
- where return types are unambiguous, they have been explicitly added
- where structural types are returned or overridden methods return
  more explicit return type, return type is not annotated (checking
  these would be work for another pull request), to avoid possible
  problems with binary compatibility
- `-Xfuture` is added to build file, so we can verify that no
  deprecated syntax remains
- demo and example files have not been touched, yet

### CODE REVIEW

**Comment by SethTisue** [comment]
this looks great! really nice to see the code getting some love. and, nice catch on enabling MiMa

one thing, though: I'm not sure that it's a good idea to leave `-Xfuture` in place, because it's a pretty big grab bag — I'd be nervous that in addition to making noise about old bad things, it might also allow questionable/experimental _new_ things that we don't want, or change the semantics of normal code. in general, `-Xfuture` is intended for experiments rather than production

**Comment by Sciss** [comment]
I can amend to remove the `-Xfuture`; it was helpful to detect all the uses of procedure syntax.

**Comment by Sciss** [comment]
What happens now?

**Comment by benhutchison** [comment]
This would be where I come in and merge! Apologies for the delay.

@Sciss can you wait for these changes to out with the next routine release?

**Comment by Sciss** [comment]
Yes sure; I have a couple of other things I would produce pull requests for; a release could wait.

**Pull request merged**
