### PR TITLE
chore(deps): bump sbt and scala versions (drop 2.11)

### PR DESCRIPTION
**Pull request by vladimir-lu**
Not sure how important 2.11 is but this is otherwise a trivial PR to update dependencies of scalac and plugins.

### CODE REVIEW

**Comment by SethTisue** [comment]
LGTM. @Sciss any objection?

**Comment by SethTisue** [comment]
@benhutchison any opinion? I couldn't find any prior discussion about perhaps dropping 2.11

**Comment by Philippus** [comment]
https://codeberg.org/sciss/SwingPlus dropped support for scala 2.11 as well.

**Comment by Philippus** [comment]
This PR is mostly been superseded by other Pull Requests. I created an [issue](https://github.com/scala/scala-swing/issues/187) about dropping support for Scala 2.11.

**Pull request closed without merging**
